title: Deep Knowledge Tracing
description: Independent Study under the guidance of <a href="http://www.cs.colorado.edu/~mozer/index.php">Prof. Michael C. Mozer</a> (Spring 2018).
show_downloads: false
google_analytics: 'UA-109066326-3'
theme: jekyll-theme-minimal